markdown: redcarpet
pygments: true

title_tag_text: Daniel Ricardo dos Santos
h1_tag_text: Daniel Ricardo dos Santos

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
